name: it-tools
working_dir: it-tools
force_image_pull: true
remove_orphans: true
---
name: stirling-pdf
working_dir: stirling-pdf
force_image_pull: true
remove_orphans: true
external_secrets:
  stirling_id: 47d179d9-9018-437a-bc68-b392007de391
  stirling_secret: ee4bf3d4-a418-43a8-a96f-b392007d4a39
---
name: auth-providers
working_dir: auth-providers
force_image_pull: true
remove_orphans: true
external_secrets:
  tinyauth_auth_secret: 4cfa6623-a514-4e7e-96fe-b39201438787
  tinyauth_oidc_id: 233069ae-f71c-434b-b85f-b3920143a2ca
  tinyauth_oidc_secret: bcd706f1-a581-48f8-b8d6-b3920143b7d0
---
name: teamspeak
working_dir: teamspeak
force_image_pull: true
remove_orphans: true


